export const MOVIES = [
    {
        id: 640146,
        title: "Ant-Man and the Wasp: Quantumania",
        year: 2023,
        rating: 6.5,
        language: "English",
        city: "Mumbai",
        poster: "https://image.tmdb.org/t/p/w500/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg",
    },
    {
        id: 502356,
        title: "The Super Mario Bros. Movie",
        year: 2023,
        rating: 7.5,
        language: "English",
        city: "Delhi",
        poster: "https://image.tmdb.org/t/p/w500/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg",
    },
    {
        id: 594767,
        title: "Shazam! Fury of the Gods",
        year: 2023,
        rating: 6.9,
        language: "English",
        city: "Bangalore",
        poster: "https://image.tmdb.org/t/p/w500/2VK4d3mqqTc7LVZLnLPeRiPaJ71.jpg",
    },
    {
        id: 76600,
        title: "Avatar: The Way of Water",
        year: 2022,
        rating: 7.7,
        language: "English",
        city: "Hyderabad",
        poster: "https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    },
    {
        id: 948713,
        title: "The Last Kingdom: Seven Kings Must Die",
        year: 2023,
        rating: 7.4,
        language: "English",
        city: "Chennai",
        poster: "https://image.tmdb.org/t/p/w500/7yyFEsuaLGTPul5UkHc5BhXnQ0k.jpg",
    },
    {
        id: 677179,
        title: "Creed III",
        year: 2023,
        rating: 7.3,
        language: "English",
        city: "Mumbai",
        poster: "https://image.tmdb.org/t/p/w500/cvsXj3I9Q2iyyIo95AecSd1tad7.jpg",
    },
    {
        id: 638974,
        title: "Murder Mystery 2",
        year: 2023,
        rating: 6.5,
        language: "English",
        city: "Delhi",
        poster: "https://image.tmdb.org/t/p/w500/s1VzVhXlqsevi8zeCMG9A16nEUf.jpg",
    },
    {
        id: 713704,
        title: "Evil Dead Rise",
        year: 2023,
        rating: 7.0,
        language: "English",
        city: "Bangalore",
        poster: "https://image.tmdb.org/t/p/w500/mIBCtPvKZQlxubxKMeViO2UrP3q.jpg",
    },
    {
        id: 315162,
        title: "Puss in Boots: The Last Wish",
        year: 2022,
        rating: 8.3,
        language: "English",
        city: "Hyderabad",
        poster: "https://image.tmdb.org/t/p/w500/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    },
    {
        id: 603692,
        title: "John Wick: Chapter 4",
        year: 2023,
        rating: 8.0,
        language: "English",
        city: "Chennai",
        poster: "https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
    },
    {
        id: 1048300,
        title: "Adrenaline",
        year: 2022,
        rating: 4.0,
        language: "English",
        city: "Mumbai",
        poster: "https://image.tmdb.org/t/p/w500/qVzRt8c2v4gGBYsnaflXVVeQ9Lh.jpg",
    },
    {
        id: 804150,
        title: "Cocaine Bear",
        year: 2023,
        rating: 6.4,
        language: "English",
        city: "Delhi",
        poster: "https://image.tmdb.org/t/p/w500/gOnmaxHo0412UVr1QM5Nekv1xPi.jpg",
    },
    {
        id: 1008005,
        title: "The Communion Girl",
        year: 2023,
        rating: 6.5,
        language: "Spanish",
        city: "Bangalore",
        poster: "https://image.tmdb.org/t/p/w500/sP6AO11a7jWgsmT9T8j9EGIWAaZ.jpg",
    },
    {
        id: 946310,
        title: "Pirates Down the Street II: The Ninjas from Across",
        year: 2022,
        rating: 6.4,
        language: "Dutch",
        city: "Hyderabad",
        poster: "https://image.tmdb.org/t/p/w500/uDsvma9dAwnDPVuCFi99YpWvBk0.jpg",
    },
    {
        id: 1104040,
        title: "Gangs of Lagos",
        year: 2023,
        rating: 5.6,
        language: "English",
        city: "Chennai",
        poster: "https://image.tmdb.org/t/p/w500/nGwFsB6EXUCr21wzPgtP5juZPSv.jpg",
    },
    {
        id: 700391,
        title: "65",
        year: 2023,
        rating: 6.3,
        language: "English",
        city: "Mumbai",
        poster: "https://image.tmdb.org/t/p/w500/rzRb63TldOKdKydCvWJM8B6EkPM.jpg",
    },
    {
        id: 758323,
        title: "The Pope's Exorcist",
        year: 2023,
        rating: 6.5,
        language: "English",
        city: "Delhi",
        poster: "https://image.tmdb.org/t/p/w500/9JBEPLTPSm0d1mbEcLxULjJq9Eh.jpg",
    },
    {
        id: 842945,
        title: "Supercell",
        year: 2023,
        rating: 6.3,
        language: "English",
        city: "Bangalore",
        poster: "https://image.tmdb.org/t/p/w500/gbGHezV6yrhua0KfAgwrknSOiIY.jpg",
    },
    {
        id: 849869,
        title: "Kill Boksoon",
        year: 2023,
        rating: 6.8,
        language: "Korean",
        city: "Hyderabad",
        poster: "https://image.tmdb.org/t/p/w500/taYgn3RRpCGlTGdaGQvnSIOzXFy.jpg",
    },
    {
        id: 1033219,
        title: "Attack on Titan",
        year: 2022,
        rating: 6.1,
        language: "English",
        city: "Chennai",
        poster: "https://image.tmdb.org/t/p/w500/qNz4l8UgTkD8rlqiKZ556pCJ9iO.jpg",
    }
];

export const CINEMAS = [
    { id: 101, name: "PVR Cinemas", location: "Juhu", city: "Mumbai" },
    { id: 102, name: "INOX Multiplex", location: "Saket", city: "Delhi" },
    { id: 103, name: "Carnival Cinemas", location: "Indiranagar", city: "Bangalore" },
    { id: 104, name: "Prasads Multiplex", location: "Banjara Hills", city: "Hyderabad" },
    { id: 105, name: "SPI Cinemas", location: "Royapettah", city: "Chennai" },
    { id: 106, name: "Gaiety Galaxy", location: "Bandra", city: "Mumbai" },
    { id: 107, name: "PVR Directors Cut", location: "Vasant Kunj", city: "Delhi" },
];

export const CITIES = ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai"];

export const SHOW_TIMINGS = ["10:30 AM", "01:45 PM", "05:00 PM", "08:15 PM", "11:00 PM"];
